# Numpy

*numpy* is an linear algebra module for data analysis

**Installation**

* pip install numpy

OR 

* conda install numpy

In [2]:
data_list=[2,4,6]

In [3]:
data_list

[2, 4, 6]

### Import module

In [4]:
import numpy as np # general form of the importing "numpy" module

### Create an array

In [5]:
arr=np.array(data_list)

In [6]:
arr

array([2, 4, 6])

### Create multidimensional array

In [7]:
data_list_two=np.array([[1,3,7],[4,6,7],[4,6,8]])

In [8]:
data_list_two

array([[1, 3, 7],
       [4, 6, 7],
       [4, 6, 8]])

In [9]:
data_list_two[1][1]

6

In [10]:
data_list_two[1,1]

6

**np.arange(start,stop,step)**

In [11]:
np.arange(5,18)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [12]:
np.arange(100,140,2)

array([100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124,
       126, 128, 130, 132, 134, 136, 138])

**np.ones(raw,column):** all elements are 1

**np.zeros(raw,column):** all elements are 0

In [13]:
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [16]:
np.zeros([4,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
np.ones([2,6])

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [18]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### create an array with desired interval and with desired step

In [19]:
np.linspace(0,80,6)

array([ 0., 16., 32., 48., 64., 80.])

In [20]:
np.linspace(100,180,4)

array([100.        , 126.66666667, 153.33333333, 180.        ])

### create unit matrix

In [21]:
np.eye(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

### random array values

In [22]:
np.random.randint(0,20)

15

In [23]:
np.random.randint(0,20)

12

In [24]:
np.random.randint(0,100,8)

array([97, 33, 68, 85,  1, 24, 39, 93])

In [25]:
np.random.rand(5)

array([0.4479804 , 0.48021286, 0.42685188, 0.53701785, 0.74765653])

In [26]:
np.random.rand(5)

array([0.74376692, 0.85443225, 0.5783024 , 0.88948186, 0.26610765])

### Gaussian distrubution(includes negatives also)

In [27]:
np.random.randn(5)

array([-0.24737272,  0.90531441, -1.31191466,  0.61670816, -0.29059748])

In [28]:
data_list_three=np.arange(25)

In [29]:
data_list_three

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

### change the dimension with same elements

In [30]:
data_list_three.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [31]:
data_list_three.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [33]:
data_list_four=np.arange(24)

In [34]:
data_list_four.reshape(2,12)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [35]:
data_list_four.reshape(6,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [36]:
new_array=np.random.randint(1,100,10)

In [37]:
new_array

array([56, 93, 33, 18, 83, 10, 14, 36, 93, 45])

### Min and Max values of the arrays

In [38]:
new_array.max()

93

In [39]:
new_array.min()

10

### Summation of the elements of the array

In [40]:
new_array.sum()

481

### Mean

In [41]:
new_array.mean()

48.1

### Where is the max or min value?

In [42]:
new_array.argmax()

1

In [43]:
new_array.argmin()

5

In [44]:
datas=np.random.randint(1,100,25)

In [45]:
datas

array([73, 32, 29, 30, 94, 51, 16, 41, 32, 23, 19, 11, 34, 13, 62, 84, 71,
       94, 18, 84,  6, 94, 91, 23, 19])

In [49]:
datas = datas.reshape(5,5)

### Find determinant

In [50]:
np.linalg.det(datas)

-476156313.9999994

In [52]:
new_datas = np.array([[2,4],[3,8]])

In [53]:
new_datas

array([[2, 4],
       [3, 8]])

In [54]:
det_of_new_array=np.linalg.det(new_datas)

In [55]:
det_of_new_array

3.999999999999999

### Index

In [56]:
array_one = np.arange(1,10)

In [57]:
array_one

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
array_one[4]

5

In [59]:
array_one[2:5]

array([3, 4, 5])

In [60]:
array_one[:4]

array([1, 2, 3, 4])

In [61]:
array_one[2:]

array([3, 4, 5, 6, 7, 8, 9])

In [62]:
array_one[::2]

array([1, 3, 5, 7, 9])

In [63]:
array_one

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
array_one[:3]=16

In [65]:
array_one

array([16, 16, 16,  4,  5,  6,  7,  8,  9])

In [66]:
array_one = np.arange(1,10)

In [67]:
array_one

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
new_array = array_one

In [69]:
new_array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
new_array[2:4]=11

In [71]:
new_array

array([ 1,  2, 11, 11,  5,  6,  7,  8,  9])

In [72]:
array_one

array([ 1,  2, 11, 11,  5,  6,  7,  8,  9])

### Important Note

**array_one** and **new_array** shows the same memory

to avoid this;

use *array_name.copy()* method

In [74]:
array_one=np.arange(1,10)

In [75]:
array_one

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
new_array = array_one.copy()

In [77]:
new_array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
new_array[1:5]=18

In [79]:
new_array

array([ 1, 18, 18, 18, 18,  6,  7,  8,  9])

In [80]:
array_one

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [81]:
array_a=np.arange(1,21)

In [82]:
array_a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [85]:
array_a=array_a.reshape([5,4])

In [86]:
array_a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [88]:
array_a[0,0]

1

**array[satır,sütun]**

In [89]:
array_a[:,:2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18]])

In [92]:
array_a[:,1:3]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19]])

In [94]:
array_a[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

In [95]:
array_a[:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [96]:
array_b=np.arange(1,10)

In [97]:
array_b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### boolean array

In [98]:
array_b > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [99]:
boolean_array_b=array_b > 5

In [100]:
boolean_array_b

array([False, False, False, False, False,  True,  True,  True,  True])

### show only **True** values in the array

In [101]:
array_b[boolean_array_b]

array([6, 7, 8, 9])

### basic operations

In [103]:
arr1=np.array([10,20,30,40])
arr2=np.array([3,5,7,9])

#### number of elements should be same !!!

In [104]:
arr1+arr2

array([13, 25, 37, 49])

In [105]:
arr1-arr2

array([ 7, 15, 23, 31])

#### inner product

In [106]:
arr1*arr2

array([ 30, 100, 210, 360])

In [107]:
arr1*2

array([20, 40, 60, 80])

In [108]:
arr2+8

array([11, 13, 15, 17])

In [109]:
arr1/10

array([1., 2., 3., 4.])

### numpy methods usage

In [110]:
np.sqrt(arr2)

array([1.73205081, 2.23606798, 2.64575131, 3.        ])

In [111]:
np.sqrt(arr1)

array([3.16227766, 4.47213595, 5.47722558, 6.32455532])

In [113]:
nice_numbers=np.array([4,9,16,25,36])

In [114]:
nice_numbers

array([ 4,  9, 16, 25, 36])

In [115]:
np.sqrt(nice_numbers)

array([2., 3., 4., 5., 6.])

### the end...